name: memekar
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_speed_dial: ^3.0.5
  image_picker: ^0.7.3
  image_gallery_saver: ^1.6.9
  permission_handler: ^6.1.1
  path_provider: ^2.0.1
  share: ^2.0.1
  emoji_picker: ^0.1.0
  flutter_material_color_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
      - assets/images/

  